swagger: "2.0"
info: 
  version: "0.0.1"
  title: Elo Manager API
host: localhost:3000
basePath: /
schemes:
  - http 
consumes: 
  - application/json
produces: 
  - application/json
paths: 
  /hotels:
    get:
      description: Retorna todos os hoteis cadastrados
      summary: Get hotels
      parameters:
        - name: name
          in: query
          type: string
        - name: email
          in: query
          type: string
        